stages:
  - "build"
  - "test"

build:
  stage: build
  image: ubuntu:latest
  script:
    - echo "Hello, world"

test:
  stage: test
  image: ubuntu:latest
  script:
    - echo "This job tests something"


deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production