version: '3.8'

services: 
  django:
    container_name: django
    port:
      - "8000:8000"
    image: chatbot:111111
    build: .
    depends_on:
      - postgres
    command: bash -c "python3 /app/manage.py runserver"
    

  postgres:
    container_name: postgres
    port:
      - "5432:5432"
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
     - vol1:/data

  
volumes:
  vol1:
    name: vol1
