version: '3.8'

services: 
  postgres:
    container_name: postgres
    networks:
      - net1
    image: ankane/pgvector:latest
    volumes:
     - vol1

  django:
    container_name: django
    networks:
      - net1
    env_file:
      - ./.env
    ports:
      - 8000:9000
    image: bootguard:latest
    build: .
    volumes:
      - bootguard:/data
    depends_on:
      postgres
    command: python3 manage.py startserver


networks:
  local:
    name: net1

  
volumes:
  bootguard:
    name: vol1
    external: true
