# Generated by Django 4.2.7 on 2023-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_bot_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
