# Generated by Django 4.2.7 on 2023-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_messages_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='last_message_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
