# Generated by Django 4.2.7 on 2023-11-21 18:25

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_bot_last_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='document_vector',
            field=pgvector.django.VectorField(blank=True, dimensions=1536),
        ),
    ]
